"""create raw_consumes table

Revision ID: 3bf69a8b19ab
Revises: 16352f6ff93a
Create Date: 2025-03-26 16:28:31.244410

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3bf69a8b19ab'
down_revision: Union[str, None] = '16352f6ff93a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('raw_consumes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.Enum('COMERCIAL', 'INDUSTRIAL', 'RESIDENCIAL', name='consumetype'), nullable=False),
    sa.Column('regiao', sa.Enum('CENTRO_OESTE', 'NORTE', 'NORDESTE', 'SUL', 'SUDESTE', name='regiao'), nullable=False),
    sa.Column('consumo', sa.Integer(), nullable=False),
    sa.Column('ano', sa.Integer(), nullable=False),
    sa.Column('mes', sa.Integer(), nullable=False),
    sa.Column('month', sa.String(), nullable=False),
    sa.Column('ipca', sa.Float(), nullable=False),
    sa.Column('dolar', sa.Float(), nullable=False),
    sa.Column('juros', sa.Float(), nullable=False),
    sa.Column('endividamento', sa.Float(), nullable=False),
    sa.Column('alcool', sa.Integer(), nullable=False),
    sa.Column('pib_mensal', sa.Float(), nullable=False),
    sa.Column('utilizacao_industria', sa.Float(), nullable=False),
    sa.Column('aco_producao', sa.Float(), nullable=False),
    sa.Column('vendas_supermercado', sa.Float(), nullable=False),
    sa.Column('caged_construcao', sa.Integer(), nullable=False),
    sa.Column('caged_energia', sa.Integer(), nullable=False),
    sa.Column('caged_informacao', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(), nullable=False),
    sa.Column('password', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('raw_consumes')
    # ### end Alembic commands ###
